### ISSUE TITLE
add contributors page

### ISSUE THREAD

**Issue by atrisovic** [atrisovic/weather-panel.github.io#15]
The page should contain:

- [ ] a list of contributors (maybe with headshots)
- [ ] how to contribute to the project (ie., by adding an issue or a PR)

**Comment by atrisovic** [comment]
Please suggest changes for updating the contributors page

**Comment by jrising** [comment]
Thanks for adding this. I wasn't happy with any way I could see to add headshots, so I just included my link on branch https://github.com/atrisovic/weather-panel.github.io/tree/addcontr.

@ks905383 I added a link to your EPIC page. Feel free to update.
